### PR TITLE
List of contests: show number of days when the contest lasts more than 24h

### LINKED ISSUE #751: Lista de concursos: mostrar # de días cuando el concurso dura más de 24h
@joemmanuel incluirá más detalles de repro steps.

### PR DESCRIPTION
**Pull request by dgarvit**
Fixes #751

### CODE REVIEW

File: frontend/www/js/omegaup/ui.js [hunk 1]
```diff
@@ -241,7 +240,12 @@ let UI = {
       seconds = '0' + seconds;
     }
 
-    var time = hours + 'h ' + minutes + 'm';
+    var time;
+    if (days === 0) {
```
Comment (lhchavez) [inline frontend/www/js/omegaup/ui.js]: how about

```javascript
var time = '';
if (days > 0)
  time += days + 'd ';
return time + hours + 'h ' + minutes + 'm';
```

**Comment by dgarvit** [comment]
@lhchavez I made the changes!

Also, can you assign me to a new issue to fix?
