### PR TITLE
fix: Browser back button does not update displayed tab on contest edit page

### LINKED ISSUE #9468: [BUG] Edit Contest page: browser back button changes URL hash but doesn't update page content
## Checklist

- [x] I have searched existing issues and confirmed this is not a duplicate (Required)

## Current Behavior

On the **Edit Contest** page (`/contest/{alias}/edit/`), clicking the navigation tabs (Edit, Add Problems, Admission Mode, Contestants, Admins, Links, Clone, Archive, Certificates) updates the page content and changes the URL hash correctly. However, when pressing the **browser back button**, only the URL hash changes  the page content remains stuck on the last tab that was clicked.

## Expected Behavior

When the browser back button is pressed, the page content should update to match the URL hash, just like when clicking a tab directly.

## If necessary, add the following information (otherwise delete this section):

**Steps to reproduce:**

1. Go to any contest's edit page (`/contest/{alias}/edit/`)
2. Click on the **"Clone"** tab → content changes to Clone, URL becomes `#clone`
3. Click on the **"Links"** tab → content changes to Links, URL becomes `#links`
4. Press the **browser back button** → URL changes back to `#clone`, but the page still shows the **Links** tab content

## Additional Context
A similar issue was previously fixed in another part of the platform.

Reference issue:
https://github.com/omegaup/omegaup/issues/9392

Reference PR:
https://github.com/omegaup/omegaup/pull/9396

The solution implemented there can be used as a reference.

https://github.com/user-attachments/assets/9078add9-07ac-4743-bfb3-c74c64b2e40d

### PR DESCRIPTION
**Pull request by anshjalan**
## Description

Add `hashchange` event listener in `edit.ts` to sync the active tab with the URL hash when the user presses the browser Back/Forward buttons. Add `@Watch` decorator in `Edit.vue` so that prop changes propagate to local component state.

This follows the same pattern used in `profile.ts` for hash-based tab navigation (PR #9396).

### Changes

- **`frontend/www/js/omegaup/contest/edit.ts`**: Added a list of valid tab hashes and a `hashchange` event listener that parses the URL hash and updates `initialTab` on the Vue instance.
- **`frontend/www/js/omegaup/components/contest/Edit.vue`**: Added `@Watch('initialTab')` so the parent prop update flows into `showTab`.

Fixes #9468

## Comments

Small, well-scoped fix (~30 lines added). The approach mirrors the existing `hashchange` handling in `frontend/www/js/omegaup/user/profile.ts`.

## Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/blob/main/frontend/www/docs/Coding-guidelines.md) of omegaUp.
- [ ] The tests were executed and all of them passed.
- [ ] If you are creating a feature, the new tests were added.
- [ ] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit, and then another Pull Request for UI + tests in Jest, Cypress or both.

https://github.com/user-attachments/assets/2dcb15aa-e7a7-4a06-b510-d8e6b5593ae3

### CODE REVIEW

File: frontend/www/js/omegaup/contest/edit.ts [hunk 1]
```diff
@@ -660,4 +682,5 @@ OmegaUp.on('ready', () => {
       });
     },
   });
+  window.addEventListener('hashchange', onHashChange);
```
Comment (pabo99) [inline frontend/www/js/omegaup/contest/edit.ts:687]: You’ll just need to remove this listener. You can take a look at this change:
https://github.com/omegaup/omegaup/pull/8776

**Comment by anshjalan** [comment]
Hi @pabo99! Thanks for the feedback. 
The onHashChange() handler in edit.ts was only updating initialTab when the hash matched a valid tab name. When navigating to a URL with no hash, the handler did nothing, leaving initialTab unchanged and preventing the Vue component's watch callback from triggering.

I have modified onHashChange() in edit.ts to explicitly set initialTab = '' when the hash is empty, and
in enhanced the @Watch('initialTab') handler in Edit.vue to call selectedTab() when initialTab is empty, ensuring the default tab is selected based on contest context.

https://github.com/user-attachments/assets/f9f4c9b1-7c1a-4a24-abda-cda74bf12f68
