### PR TITLE
Webpack cache busting grader directory

### LINKED ISSUE #7493: [BUG] The editor does not load properly because of "reading properties of null" exception.
## Current Behavior
Sometimes when loading a problem, the editor bugs out.

editor-error

## Expected Behavior

The editor should load normally at all times without bugging.

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. go to any problem
	2. refresh a couple of times and this bug occurs
	3. 
	4. 
*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4):
	* Operating System and version (desktop or mobile):
	* Link to the site where this issue occurs:
	* Screenshot:

### PR DESCRIPTION
**Pull request by HNOONa-0**
# Description

Problem:
Browser was caching `ephemeral.js`. So, any changes made on `ephemeral.js`  will not be reflected as the browser will **return cached version** of `ephemeral.js` not updated one.
grader-cache-1
Why is it doing that for `ephemeral.js`?
I think it's because it's a large file (9 MB) so the browser decides to cache that file, but I'm not sure.
Solution:
Implement cache busting for `webpack.config-grader` file. Put simply, cache busting is a way to tell the browser **not to  cache certain files/assets when we don't want them to**, like in this scenario. What I did was I moved `index.html` and `index-light.html` to a separate directory called `templates`. Then, I use the `HtmlWebpackPlugin` to init the `index.html` and `index-light.html` with actual hashed `ephemeral.js` script. Now it works properly.

Fixes: #7524

# Comments
1) Each time we update `ephemeral.js` and new hashed script is created in `dist` directory. We need to find a way to `clean` previous hashed when creating new one.
2) Put resulting `index.html` and `index-light.html` created by the plugin in `.gitignore` file.
3) Webpack will `defer` the script, there is no `async` scriptLoading. I believe deferring the script fixes #7493
# Checklist:

- [ ] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [ ] The tests were executed and all of them passed.
- [ ] If you are creating a feature, the new tests were added.
- [ ] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Comment by RingoTC** [comment]
I think we can activate the "Disable cache" option in dev tools rather than modify the source code because cache is a useful mechanism for speeding up.

image

**Comment by HNOONa-0** [comment]
> I think we can activate the "Disable cache" option in dev tools rather than modify the source code because cache is a useful mechanism for speeding up.
> 
> image

These changes will keep caching files as necessary, when compiling a file whose contents have changed the hash code will change and browser will load this new version.

If you don't make any new changes, the hash code wont change and browser will load cached version.

**Comment by HNOONa-0** [comment]
This test is not deterministic it was first expecting 14 instead of 12 now its expecting 12 instead of 14. i have not touched any logic beside webpack config what is going on?

**Comment by HNOONa-0** [comment]
Recap:
1) Added `index.html`, `index-light.html` to a separate directory called `template`.
2) Later use those template to init the `html` files with correct hashed version of `ephemeral.js` using `HtmlWebpackPlugin`. This is to preform cache busting.
3) Installed a new package `clean-webpack-plugin` that will delete unused scripts so that `dist` directory doesn't get over-populated with unused script files.

I installed the package using `npm`. This is a working fix. 
@pabo99 Please take a look.

**Comment by pabo99** [comment]
Could you please resolve the conflicts?

**Comment by HNOONa-0** [comment]
my bad i accidentally closed this pr

**Comment by HNOONa-0** [comment]
> This test is not deterministic it was first expecting 14 instead of 12 now its expecting 12 instead of 14. i have not touched any logic beside webpack config what is going on? Screenshot_2024-04-04-22-31-28-65_40deb401b9ffe8e1df2f1cc5ba480b12

Hmm I think we should remove the line that validates submissions line count.

**Comment by HNOONa-0** [comment]
I figured out why the this test fails. Sometimes, the modal mounts after the editor.
The modal mounts first->modal is empty->get 12 lines.
The modal mounts after the editor->editor code get copied over to the modal->test writes `main.cpp` contents-> not 12 lines anymore.

[Screencast from 04-12-2024 06:18:56 PM.webm](https://github.com/omegaup/omegaup/assets/59091536/c736e03a-d193-4a71-a130-6d90ecc9b755)

**Comment by HNOONa-0** [comment]
d

**Comment by HNOONa-0** [comment]
just to be transparent about the changes, here how the updated config file affect compilation:

[Screencast from 04-12-2024 08:24:30 PM.webm](https://github.com/omegaup/omegaup/assets/59091536/32f43971-0f9b-471f-93fd-96a67e1162ee)

File: cypress/support/pageObjects/coursePage.ts [hunk 1]
```diff
@@ -248,7 +248,6 @@ export class CoursePage {
 
       cy.wrap(userCode).as('userCodeLines');
     });
-    cy.get('@userCodeLines').should('have.length', 12);
```
Comment (pabo99) [inline cypress/support/pageObjects/coursePage.ts:251]: Instead removing this line, do you think this can work:
```ts
cy.get('@userCodeLines').should('have.length.above', 11);
```
?

**Review by pabo99 — COMMENTED** [review]
It works great! Thank you for resolving it!

Just one minor suggestion

File: cypress/support/pageObjects/coursePage.ts (hunk 1 above)
Comment (HNOONa-0) [reply cypress/support/pageObjects/coursePage.ts:251]: Yes this works with either scenarios.

**Review by pabo99 — APPROVED** [review]
LGTM!

**Review by heduenas — APPROVED** [review]
