### PR TITLE
Fix open redirection vulnerability

### LINKED ISSUE #1883: Open redirect vulnerability in login page
Sample malicious url `https://omegaup.com/login/?redirect=https%3A//www.example.com/`
## Current behaviour
Redirect URL is not filtered, so that users are vulnerable to phising attack

## Expected behaviour
Redirect URL should be only available with only `omegaup.com` domain

## Possible solution
Add redirect validation in https://github.com/omegaup/omegaup/blob/0f63ff8b4c477155b2231ab4f79e1eb66e69253d/frontend/www/login.php#L48

### PR DESCRIPTION
**Pull request by SpaceWhite**
Fix #1883

### CODE REVIEW

File: frontend/www/login.php [hunk 1]
```diff
@@ -46,10 +46,16 @@
 
 if ($c_Session->CurrentSessionAvailable()) {
     if (isset($_GET['redirect'])) {
-        die(header('Location: ' . $_GET['redirect']));
-    } else {
-        die(header('Location: /profile/'));
-    }
+        $redirect_hostname = parse_url($_GET['redirect'], PHP_URL_HOST);
+        //In case malformed URL is given redirect
+        if ($redirect_hostname !== false) {
```
Comment (lhchavez) [inline frontend/www/login.php]: do you mind combining the two conditions?

```php
if (in_array($redirect_hostname, $allowed_hosts, true))
```

given that you're asking for strict compariton, the `false` check is not needed :D
