### PR TITLE
Difficulty and Quality Filter Labels break mid word on mobile viewport 

### LINKED ISSUE #9430: [BUG] Difficulty and Quality filter labels break mid-word on mobile viewports in problem collection pages
## Current Behavior

On the problem collection pages (e.g., `/problem/collection/problemLevelIntermediateMathsInProgramming/`), the **Difficulty** and **Quality** filter sidebar labels break mid-word on mobile/tablet viewports (e.g., "Difficu lty", "Qualit y"), making them unreadable. The radio button options also appear cramped and misaligned.

## Expected Behavior

The "Difficulty" and "Quality" headings and their radio button options should display correctly without word-breaking, regardless of screen size.

## Root Cause

The root `<div>` elements in both [FilterDifficulty.vue](cci:7://file:///c:/Users/BIT/Desktop/omegaup/frontend/www/js/omegaup/components/problem/FilterDifficulty.vue:0:0-0:0) and [FilterQuality.vue](cci:7://file:///c:/Users/BIT/Desktop/omegaup/frontend/www/js/omegaup/components/problem/FilterQuality.vue:0:0-0:0) use Bootstrap grid column classes (`col-6 col-sm-3 col-lg-12`) that were designed for a Bootstrap `row` parent. However, in [CollectionList.vue](cci:7://file:///c:/Users/BIT/Desktop/omegaup/frontend/www/js/omegaup/components/problem/CollectionList.vue:0:0-0:0), these components are placed inside a `filters-sidebar` div (a fixed 250px flexbox container, **not** a Bootstrap row).

On smaller viewports, `col-sm-3` restricts the width to 25% of the parent (~62px), which is far too narrow for the content causing the text to wrap mid-word.

**Affected files:**
- [frontend/www/js/omegaup/components/problem/FilterDifficulty.vue](cci:7://file:///c:/Users/BIT/Desktop/omegaup/frontend/www/js/omegaup/components/problem/FilterDifficulty.vue:0:0-0:0) (line 2)
- [frontend/www/js/omegaup/components/problem/FilterQuality.vue](cci:7://file:///c:/Users/BIT/Desktop/omegaup/frontend/www/js/omegaup/components/problem/FilterQuality.vue:0:0-0:0) (line 2)

## Steps to Reproduce

1. Go to **Problems → Browse Problem Collections**
2. Click on any collection (e.g., "Intermediate Level – Mathematics in Programming")
3. View the page on a mobile viewport (or use browser DevTools to emulate a device like iPhone 12 Pro)
4. Observe the **Difficulty** and **Quality** filter sections in the left sidebar

Image

### PR DESCRIPTION
**Pull request by thunderbird7413**
### Problem
On problem collection pages, the Difficulty and Quality filter labels (e.g., "Difficu lty", "Qualit y") were breaking mid-word on mobile/tablet viewports. The radio button options also appeared cramped and misaligned.

### Root Cause 
Both  **FilterDifficulty.vue** and **FilterQuality.vue** had Bootstrap grid classes col-6 col-sm-3 col-lg-12 on their root `<div>`. The `col-sm-3` class restricts the element width to 25% of its parent on small viewports. However, in **CollectionList.vue**, these components are placed inside a fixed 250px filters-sidebar flexbox container — not a Bootstrap .row. This caused the computed width to be ~62px, far too narrow for the content, resulting in mid-word text wrapping.

### Fix
Removed the Bootstrap grid column classes `(col-6 col-sm-3 col-lg-12)` from the root `<div>` in both components. Since layout is controlled by the sidebar container, no grid classes are needed — the cards now fill the full sidebar width correctly at all viewport sizes.

Files Changed
```
frontend/www/js/omegaup/components/problem/FilterDifficulty.vue
frontend/www/js/omegaup/components/problem/FilterQuality.vue
```

Fixes #9430

### CODE REVIEW

**Comment by Yashagarwal9798** [comment]
Hey @thunderbird7413, thanks for working on this! Could you please add a screenshot of the changes to the PR description?

**Comment by thunderbird7413** [comment]
@Yashagarwal9798, I cant test it manually on the browser because there are no courses in the category like intermediate, easy etc. They are 0, so I cant access them. If there is any other way to get the courses then surely I'll do that.

**Comment by pabo99** [comment]
> @Yashagarwal9798, I cant test it manually on the browser because there are no courses in the category like intermediate, easy etc. They are 0, so I cant access them. If there is any other way to get the courses then surely I'll do that.

There is a somewhat tedious way to populate the collections view, but it will allow you to see the collections:

Go to the DB and update `quality_seal` for all problems:

```sql
UPDATE Problems set quality_seal = 1 WHERE problem_id > 0;
```
Then manually run the `aggregate_feedback.py` cronjob from inside the container:
```bash
$ ./stuff/cron/aggregate_feedback.py 
```

**Comment by thunderbird7413** [comment]
> > @Yashagarwal9798, I cant test it manually on the browser because there are no courses in the category like intermediate, easy etc. They are 0, so I cant access them. If there is any other way to get the courses then surely I'll do that.
> 
> There is a somewhat tedious way to populate the collections view, but it will allow you to see the collections:
> 
> Go to the DB and update `quality_seal` for all problems:
> 
> ```sql
> UPDATE Problems set quality_seal = 1 WHERE problem_id > 0;
> ```
> 
> Then manually run the `aggregate_feedback.py` cronjob from inside the container:
> 
> ```shell
> $ ./stuff/cron/aggregate_feedback.py 
> ```

@pabo99, I am getting this
image

**Comment by thunderbird7413** [comment]
@pabo99, All the changes as suggested by you have been done. Plss review them😊

**Comment by thunderbird7413** [comment]
**1. Whenever a UI change is made, it’s recommended to include before and after screenshots so reviewers can clearly see what needs to be checked.**
These are the before and after scenarios for the word break at different viewports for the filter labels.
**Before->**
image
**After->**
image

**2. Is there a way to keep the same padding for the filter cards (quality and difficulty) across all breakpoints where they appear? I noticed that at some point one of the paddings seems to be lost.**
Gave a uniform padding of `p-3`
image
image

**3. Could the title be placed one level above the "Back to collections" button? That way it could take the full width of the screen and wouldn’t get cut off as shown in the screenshot:**
This has also been done by removing the div with class as `row `and replacing it with the `h1` eventually placing it  above the "Back to collections" button, previously It was inside a row and there were two columns,  the button and the title due to which it was not able to take full width. 
image

**4. Is there a way to hide the filter cards on smaller screens? Possibly when the viewport gets too narrow?**
Yes we can do this by adding media query inside the collectionList.vue file. When the viewport gets too narrow we can hide them. You can see in the image. 
image

File: frontend/www/js/omegaup/components/problem/CollectionList.vue [hunk 1]
```diff
@@ -1,14 +1,10 @@
...
-    <div class="row">
-      <div class="col col-md-3 d-flex align-items-center">
-        <a href="/problem/collection/" data-nav-problems-collection>{{
-          T.problemCollectionBackCollections
-        }}</a>
-      </div>
-      <div class="col mb-4">
-        <h1 class="title-font p-0">{{ title }}</h1>
-      </div>
+    <h1 class="title-font p-0 mb-2">{{ title }}</h1>
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/problem/CollectionList.vue]: Could you center the title?

Comment (thunderbird7413) [reply frontend/www/js/omegaup/components/problem/CollectionList.vue]: Yes I have done that

**Comment by thunderbird7413** [comment]
> Excellent progress!
> 
> Regarding this point:
> 
> > Is there a way to hide the filter cards on smaller screens? Possibly when the viewport gets too narrow?
> 
> What I meant was whether it would be possible to hide the entire column so that the problem list can take up the full width of the space. If possible, we could implement a drawer so it appears when pressing the button that we already have

Yes, I have updated the changes and implmented the required functionality.

File: frontend/www/js/omegaup/components/problem/CollectionList.vue [hunk 2]
```diff
@@ -269,4 +299,55 @@ export default class CollectionList extends Vue {
...
+    top: 0;
+    left: 0;
+    z-index: 20;
+    width: min(18rem, 85vw);
+    min-width: min(18rem, 85vw);
+    height: 100%;
+    padding-right: 0.5rem;
+    padding-left: 0.5rem;
+    background: var(--header-color, #fff);
+    border-right: 1px solid var(--border-color, #ddd);
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/problem/CollectionList.vue]: You can add these variables to _**_variables.scss**_. Maybe you can add a suffix to indicate which view they belong to.

Comment (thunderbird7413) [reply frontend/www/js/omegaup/components/problem/CollectionList.vue]: Okay, Implemented.
