### PR TITLE
fixed the composing window size

### LINKED ISSUE #4850: [FEATURE] Aumentar el tamaño de la cajita de texto de la vista de editar redacción
Lo ideal sería que por default tuviera el mismo tamaño que el preview de la derecha.

image

### PR DESCRIPTION
**Pull request by antedotee**
Before:
image

After:
image

Fixes #4850

### CODE REVIEW

File: frontend/www/js/omegaup/components/problem/creator/solution/SolutionTab.vue [hunk 1]
```diff
@@ -169,4 +169,36 @@ export default class SolutionTab extends Vue {
 .wmd-button-bar {
   background-color: var(--wmd-button-bar-background-color);
 }
+
+.row {
+  display: flex;
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/problem/creator/solution/SolutionTab.vue]: It looks like this style is already part of the row class in Bootstrap 4, so there's no need to add it here
```suggestion
```

File: frontend/www/js/omegaup/components/problem/creator/solution/SolutionTab.vue [hunk 2]
```diff
@@ -169,4 +169,36 @@ export default class SolutionTab extends Vue {
...
+
+  .col-md-6 {
+    display: flex;
+    flex-direction: column;
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/problem/creator/solution/SolutionTab.vue]: These styles can be handled using Bootstrap 4 classes:
```css
d-flex flex-column
``` 
You can add them directly in the places where you use `col-md-6`

File: frontend/www/js/omegaup/components/problem/creator/solution/SolutionTab.vue [hunk 3]
```diff
@@ -169,4 +169,36 @@ export default class SolutionTab extends Vue {
...
+      .wmd-input {
+        flex: 1;
+        min-height: 400px;
+        height: auto !important;
+        resize: vertical;
+      }
+    }
+
+    &:last-child {
+      omegaup-markdown {
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/problem/creator/solution/SolutionTab.vue]: The linter doesn't accept this as a valid selector. Instead, you can try using the generic `data-attribute` of the `Markdown` component:

```suggestion
     [data-markdown-statement] {
```
Or, if you want to be more specific, you can use the `data-attribute` assigned in this component. Both approaches yield the same result

File: frontend/www/js/omegaup/components/problem/creator/solution/SolutionTab.vue [hunk 4]
```diff
@@ -169,4 +169,36 @@ export default class SolutionTab extends Vue {
...
+        flex: 1;
+        min-height: 400px;
+        overflow-y: auto;
+        border: 1px solid #ddd;
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/problem/creator/solution/SolutionTab.vue]: Can this color be added to the variables file and used here just like it's done on line 170?

File: frontend/www/js/omegaup/components/problem/creator/statement/StatementTab.vue [hunk 5]
```diff
@@ -105,4 +105,36 @@ export default class StatementTab extends Vue {
...
 }
+
+.row {
+  display: flex;
+
+  .col-md-6 {
+    display: flex;
+    flex-direction: column;
+
+    &:first-child {
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/problem/creator/statement/StatementTab.vue]: Is it necessary to specify that it only applies to the first child? It looks like you're already using a specific selector inside, which should only target that element.

Also, since you're using `scoped`, the styles in this file should be limited to this component and its children.

If it's not necessary, you can remove it and use the selector directly. The same approach could work where you're using  `last-child`
