### PR TITLE
Fix(#9765): Display API Tokens table as vertical card layout on mobile

### LINKED ISSUE #9765: [FEATURE] Display API Tokens table as vertical card layout on mobile
## Checklist

- [x] I have searched existing issues and confirmed this is not a duplicate (Required)

As a **user**, I want the **API Tokens table to display as a vertical card layout on mobile screens** so that **each token's details are readable without horizontal scrolling**.

## Context

The current fix for the API Tokens table on mobile (PR #8797) makes the table horizontally scrollable, but on small viewports this still requires side-scrolling to read token details, which is a poor experience.

A vertical/stacked card layout where each token is displayed as a card with labeled fields would make the information readable at a glance on mobile without any scrolling direction change.

This was also suggested by @pabo99 in the review of PR #8797.

The relevant component is `frontend/www/js/omegaup/components/user/ManageApiTokens.vue`.

### PR DESCRIPTION
**Pull request by shauryag2002**
# Description
This pull request improves the user experience for managing API tokens on different devices by introducing a responsive design to the `ManageApiTokens.vue` component. Now, API tokens are displayed in a standard table on desktop/tablet screens and in a mobile-friendly card layout on smaller devices. The main changes are as follows:

**Responsive layout for API tokens:**

* Added a conditional layout to display API tokens as a table on desktop/tablet (`.d-none .d-sm-block`) and as vertically-stacked cards on mobile (`.d-block .d-sm-none`) in `ManageApiTokens.vue`. [[1]](diffhunk://#diff-c403417927a82635ddbbd6745d14f5bfc51da64c7b1f345172bdfa163434744bL32-R34) [[2]](diffhunk://#diff-c403417927a82635ddbbd6745d14f5bfc51da64c7b1f345172bdfa163434744bR67-R121)

**Mobile card UI implementation:**

* Implemented a new `.api-token-card` style for mobile, including visual enhancements such as borders, padding, and a shadow, as well as a flexbox-based row layout for token details and actions.

**Table markup simplification:**

* Simplified the table markup by removing unnecessary `data-label` attributes, since these are no longer needed for the desktop/tablet view.

[Screencast from 2026-04-15 22-56-28.webm](https://github.com/user-attachments/assets/2d0a55b7-879d-4218-930b-eb28861f5e37)

Fixes: #9765 

# Comments

Add any comments for the reviewers (e.g., indicating the beginning of the revision, something where the reviewer needs to pay special attention, etc.). If  there are no extra comments this section can be deleted.

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/blob/main/frontend/www/docs/Coding-guidelines.md) of omegaUp.
- [ ] The tests were executed and all of them passed.
- [ ] If you are creating a feature, the new tests were added.
- [ ] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

File: frontend/www/js/omegaup/components/user/ManageApiTokens.vue [hunk 1]
```diff
@@ -29,40 +29,95 @@
...
-              >
-                {{ T.apiTokenRevoke }}
-              </button>
-            </td>
-          </tr>
-        </tbody>
-      </table>
+    <div v-else>
+      <!-- Desktop / tablet: standard table -->
+      <div class="table-responsive d-none d-sm-block">
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/user/ManageApiTokens.vue]: Could you use the table layout from the 768px (md) breakpoint? The screen is still large enough for this.
Below 768px, switch to vertical cards.

File: frontend/www/js/omegaup/components/user/ManageApiTokens.vue [hunk 2]
```diff
@@ -122,4 +177,51 @@ export default class ManageApiTokens extends Vue {
     vertical-align: middle;
   }
 }
+
+// Mobile card layout
+.api-token-card {
+  border: 1px solid #dee2e6;
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/user/ManageApiTokens.vue]: Could you add this and the other colors used as variables in the `frontend/www/sass/base/_variables.scss` file?

**Review by pabo99 — COMMENTED** [review]
Great change. We should standardize tables to always have a desktop and a mobile-friendly view. This might be a larger task, so we can leave it for now.

Just a couple of suggestions

File: frontend/www/js/omegaup/components/user/ManageApiTokens.vue (hunk 1 above)
Comment (shauryag2002) [reply frontend/www/js/omegaup/components/user/ManageApiTokens.vue]: @pabo99 , Done :+1:

File: frontend/www/js/omegaup/components/user/ManageApiTokens.vue (hunk 2 above)
Comment (shauryag2002) [reply frontend/www/js/omegaup/components/user/ManageApiTokens.vue]: @pabo99 , Done :+1:

**Comment by shauryag2002** [comment]
Updated Video after new changes:


https://github.com/user-attachments/assets/5f7d9db7-bad1-427f-99d8-d1feb19bbc1a

**Review by pabo99 — APPROVED** [review]
Thank you!
