### PR TITLE
Fix misalignment of New course button on /course/mine page

### LINKED ISSUE #9320: [BUG] Fix misalignment of "New course" button on /course/mine page
### Summary

This PR fixes a layout misalignment affecting the "New course"
button on the `/course/mine` page.

Previously, the button was positioned using a `float-right` container inside
`.card-body`, which caused inconsistent vertical spacing and visual
misalignment relative to the "Courses I manage" header.

This PR replaces the float-based layout with a flexbox-based layout while
preserving the existing component structure and behavior.

### Problem

The current implementation uses:

```vue
<div class="card-body pb-0">
  <div class="float-right">
    <a class="btn btn-primary" href="/course/new/">
      {{ T.courseNew }}
    </a>
  </div>
</div>
```

This creates:

- Inconsistent spacing between header and button
- Slight vertical misalignment
- Visual detachment from the card header
- Use of deprecated float-based layout
- Less predictable rendering across screen sizes

### Solution

The layout has been updated to use flexbox:

```vue
<div
  class="card-body pb-0 d-flex justify-content-end"
  v-if="isMainUserIdentity"
>
  <a class="btn btn-primary" href="/course/new/">
    {{ T.courseNew }}
  </a>
</div>
```

This change:

- Aligns the button consistently with the card layout
- Removes reliance on float-based positioning
- Uses modern Bootstrap layout utilities
- Keeps the original DOM structure intact

### UX Improvements

This update improves the user experience by:

- Making the primary action ("New course") easier to locate
- Providing consistent spacing inside the card
- Improving visual hierarchy
- Ensuring predictable rendering across screen sizes

The button now appears clearly as the primary action for the
"Courses I manage" section.

### Technical Notes

- No logic changes
- No API changes
- No store changes
- No prop changes
- No behavior changes

Only layout classes were modified.

### Testing

Tested locally on:

- `/course/mine`
- Different viewport sizes
- Logged-in main identity user
- Non-main identity user (button hidden correctly)

No regressions observed.

### Risk Assessment

Low risk.

This change only replaces `float-right` with a flexbox layout and does not
modify any functional code.

### Motivation

This improvement contributes to UI consistency and modernizes layout usage
across omegaUp components.

Small UI polish improvements like this help maintain a clean and predictable
interface, especially on pages with primary actions such as course creation.

### Before-

Image
Image
Image

### PR DESCRIPTION
**Pull request by abhinavsingh-hub**
### Fix misalignment of "New course" button on /course/mine page

Closes #9320

## Summary

This PR fixes a UI alignment issue affecting the **"New course"** button on the `/course/mine` page.

Previously, the button was placed inside a separate container using `float-right`, which caused inconsistent vertical alignment relative to the section header. This resulted in a visually unbalanced layout and reduced interface clarity.

This PR replaces the float-based layout with a flexbox-based structure, ensuring consistent alignment between the section title and the action button.

## Before

- Button positioned inside a separate card-body container
- Vertical misalignment with section header
- Inconsistent spacing
- Float-based layout harder to maintain

## After

- Button aligned horizontally with "Courses I manage" header
- Consistent vertical spacing
- Cleaner layout structure
- Modern flexbox-based positioning

## Technical Changes

- Replaced `float-right` layout with flexbox container
- Moved button into header layout structure
- Improved alignment consistency
- No functional changes

File modified:

frontend/www/js/omegaup/components/course/Mine.vue

## Testing

Tested locally:

1. Open `/course/mine`
2. Verify button alignment with section header
3. Confirm layout remains stable across tabs
4. Confirm no functional regressions

The change is purely visual and does not affect functionality.

## Before:

Screenshot 2026-02-25 at 5 17 49 PM

Screenshot 2026-02-25 at 5 18 03 PM

Screenshot 2026-02-25 at 11 16 45 PM

## After:

Screenshot 2026-02-26 at 12 45 26 AM

Screenshot 2026-02-25 at 11 19 20 PM

### CODE REVIEW

**Comment by abhinavsingh-hub** [comment]
@pabo99  Could you please take a look at this PR when convenient?
I would appreciate any feedback and will address any requested changes promptly.
Thank you.

File: frontend/www/js/omegaup/components/course/Mine.vue [hunk 1]
```diff
@@ -1,18 +1,28 @@
 <template>
   <div class="card">
-    <h3 class="card-header mb-0">{{ T.courseListAdminCourses }}</h3>
-    <div class="card-body pb-0">
-      <div v-if="isMainUserIdentity" class="float-right">
-        <a class="btn btn-primary" href="/course/new/">{{ T.courseNew }}</a>
-      </div>
+
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/course/Mine.vue]: For consistency with the rest of the template, could you remove the blank lines? They’re usually useful in larger components when it's worth separating blocks. In this case, it doesn't seem necessary.

**Comment by abhinavsingh-hub** [comment]
hey @pabo99 !!

Thanks for the earlier feedback and suggestion regarding improving the empty state.

Apologies for the delay in pushing the update. While implementing the change I also spent some time configuring a few issues I had faced in my system local and along the way explored the course-related components and the repository’s i18n pipeline to better understand how UI state and translations are structured across the codebase, causing a bit delay in my response. Although, this has helped me to ensure the update integrates cleanly with the existing component structure and translation workflow.

Changes in this update:
- Implemented an explicit empty-state UI when no courses are present.
- Added a centered message, icon, and a more prominent call-to-action button for creating the first course.
- The component now checks `filteredCourses` groups to determine whether any courses exist before rendering the table vs the empty state.
- Added the corresponding i18n keys (`courseListEmptyTitle`, `courseListEmptyDescription`) across all template language files (`en`, `es`, `pt`, and `pseudo`).
- Ran the repository lint/i18n scripts so the generated `lang.*.ts` and `lang.*.json` files stay synchronized with the `.lang` templates.

Screenshot 2026-03-04 at 12 56 26 AM
Screenshot 2026-02-25 at 11 19 20 PM


The branch has been updated accordingly and is ready for review. Please let me know if there are any refinements you’d like me to make.

Looking forward!!
Regards

**Comment by abhinavsingh-hub** [comment]
Also @pabo99, 
I was not able to find an option to delete any of the courses I had created or am part of, is there any way for it that I might have missed or is it something I should look towards working upon as a separate issue? Would love your guidance here

File: frontend/www/js/omegaup/components/course/Mine.vue [hunk 2]
```diff
@@ -34,5 +66,15 @@ export default class Mine extends Vue {
...
   T = T;
   ui = ui;
+
+  get hasCourses(): boolean {
+    const filtered = this.courses.admin.filteredCourses;
+
+    if (!filtered) return false;
+
+    return Object.values(filtered).some(
+      (group: any) => group.courses && group.courses.length > 0,
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/course/Mine.vue]: Normally we avoid using the any type. Instead, you can use the correct type; in this case it would be `types.CoursesByTimeType`. Also, in the expression you could use the optional chaining operator so that it looks something like this:
```suggestion
      (group: types.CoursesByTimeType) => group.courses?.length > 0,
```

File: frontend/templates/es.lang [hunk 3]
```diff
@@ -640,6 +640,8 @@ courseList = "Lista de cursos"
 courseListAdminCourses = "Cursos que administro"
 courseListArchivedCourses = "Cursos archivados"
 courseListCurrentCourses = "Cursos actuales"
+courseListEmptyDescription = "Create your first course to start organizing lessons and students."
```
Comment (pabo99) [inline frontend/templates/es.lang]: nit:
```suggestion
courseListEmptyDescription = "Crea tu primer curso para comenzar a organizar lecciones y estudiantes."
```

**Review by pabo99 — COMMENTED** [review]
This change turned out excellent, just a couple of suggestions and it's ready.

**Comment by abhinavsingh-hub** [comment]
duly noted @pabo99 !!
and thank you for the guidance, I have changed it accordingly and will keep this things in mind for the future as well, please review it once and let me know if anything is still yet to improve.
also, can you please confirm me about being unable to find the delete my courses option I had inquired about earlier?
Regards

**Comment by abhinavsingh-hub** [comment]
Thanks @pabo99  for pointing that out! I've run the lint fix command to propagate the translation changes and pushed the updated files. Please let me know if anything else needs adjustment.
Also, I tried the archive method in my local but was unable to reproduce the desired results, hence got confused
