### PR TITLE
#9676 Improve empty state for Teams Groups page

### LINKED ISSUE #9676: [FEATURE] Improve empty state when no teams groups have been created
## Checklist

- [x] I have searched existing issues and confirmed this is not a duplicate (Required)

## Description

Currently, when no teams groups have been created, the interface only displays an empty table. This can make the page feel incomplete and may confuse users about what to do next.

As a suggestion, we could replace this empty table with a more helpful empty state, similar to what GitHub uses in some sections:

- Show a centered placeholder inside the container/card.
- Add a relevant _**FontAwesome**_ icon to make the empty state more visually engaging.
- Include a short title indicating that no teams groups have been created yet.
- Add a brief description encouraging the user to create their first teams group.
- Display the "_**Create new teams group**_" button prominently within this empty state (centered).

Image

This would make the interface more intuitive and guide users toward the next action.

Once the user creates their first teams group, the interface should return to the current layout where the list of groups is displayed normally.

## Steps to reproduce

1. Go to the top-right menu (where the user profile is displayed).
2. Select the "_**My teams groups**_" option.
3. Observe that an empty table is displayed.

## Context

We are applying these styles in other places where empty tables are displayed

### PR DESCRIPTION
**Pull request by abhinavsingh-hub**
## 🧩 Improve empty state for Teams Groups page 
Fixes: #9676 

### Description
Currently, when no teams groups have been created, the interface displays an empty table. This can be confusing for users and does not provide clear guidance on what to do next.

This PR introduces a user-friendly empty state for the Teams Groups page, improving usability and maintaining consistency with other parts of the platform (e.g., course list page).

---

### Changes implemented
- Added a computed property (`hasTeamsGroups`) to detect when no teams groups exist
- Replaced the empty table with a centered empty state UI including:
  - FontAwesome icon (`users`)
  - Title and description
  - Prominent "Create new teams group" button
- Preserved existing table layout when teams groups are present
- Added translations for:
  - en
  - es
  - pt
  - pseudo
- Followed the same empty state pattern used in `course/mine`

---

###  Impact
- Improves user experience by guiding users when no data is present
- Reduces confusion for first-time users
- Ensures UI consistency across the platform

---

### Checklist
- [x] UI updated with empty state
- [x] Translations added for all languages
- [x] Tests updated/added
- [x] No lint or type errors

### CODE REVIEW

**Comment by abhinavsingh-hub** [comment]
Hey @pabo99 !!

I have solved this issue using the similar logic as #9321 

Please review and let me know if anything has to be altered

Regards

**Comment by abhinavsingh-hub** [comment]
Updated Cypress test to handle multiple matching elements after introducing the empty state UI.

Since there are now two "Create new teams group" buttons (top action button and empty state CTA), the selector was matching multiple elements and causing test failure. Added `.first()` to ensure a single element is targeted.

This keeps the existing test logic intact while resolving the ambiguity introduced by the UI improvement.

**Review by pabo99 — COMMENTED** [review]
Could you add a screenshot?

File: frontend/www/js/omegaup/components/teamsgroup/List.vue [hunk 1]
```diff
@@ -1,15 +1,16 @@
 <template>
   <div>
     <div class="mb-3 text-right">
-      <a class="btn btn-primary mx-1" href="/teamsgroup/new/">{{
-        T.teamsGroupsCreateNew
-      }}</a>
+      <a class="btn btn-primary mx-1" href="/teamsgroup/new/">
+        {{ T.teamsGroupsCreateNew }}
+      </a>
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/teamsgroup/List.vue:6]: Can you hide this element when there are no teams groups created? That way you don’t have to modify the Cypress tests and can revert the change you made

File: frontend/www/js/omegaup/components/teamsgroup/List.vue [hunk 2]
```diff
@@ -34,6 +37,26 @@
...
+        </h4>
+
+        <p class="text-muted mb-4">
+          {{ T.teamsGroupEmptyDescription }}
+        </p>
+
+        <a class="btn btn-primary btn-lg" href="/teamsgroup/new/">
+          {{ T.createTeamsGroup }}
+        </a>
+      </div>
```
Comment (pabo99) [inline frontend/www/js/omegaup/components/teamsgroup/List.vue:59]: I’m thinking we could turn this into a reusable component where we pass:

- Icon  
- Title  
- Description  
- Button text  
- Button/link action  

This way, we can update the styling globally. But that can be done in a separate change. For now, this looks good.

**Review by pabo99 — COMMENTED** [review]
Just a minor suggestion and we’re good

**Comment by abhinavsingh-hub** [comment]
Thanks for the suggestion @pabo99!

I’ve updated the UI to hide the top "Create new teams group" button when there are no teams groups. This ensures that only a single call-to-action is present in the empty state and avoids selector ambiguity.

I’ve also reverted the Cypress test change accordingly.

Regarding the reusable empty state component, I agree it would be a valuable improvement. If agreed, I’ll open a separate issue to track that enhancement.

**Review by pabo99 — APPROVED** [review]
Thanks!
